Class Treinamento.Teste Extends %Persistent
{
Storage Default
{
<Data name="TesteDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Treinamento.TesteD</DataLocation>
<DefaultData>TesteDefaultData</DefaultData>
<IdLocation>^Treinamento.TesteD</IdLocation>
<IndexLocation>^Treinamento.TesteI</IndexLocation>
<StreamLocation>^Treinamento.TesteS</StreamLocation>
<Type>%Storage.Persistent</Type>
}
}
